ARG DOCKER_IMAGE=python:3.13.12-trixie
ARG OS_VERSION_CODENAME=trixie
ARG POETRY_VERSION=2.3.2
ARG TASKFILE_VERSION=3.49.1

# -----------------------------------------------------------------------------
# BASE
# ------------------------------------------------------------------------------
FROM $DOCKER_IMAGE AS base

# Install packages
RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        sudo \
        rsync \
        ca-certificates \
        systemd \
        systemd-sysv \
        dbus \
        dbus-user-session \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && truncate -s 0 /var/log/*log

# ------------------------------------------------------------------------------
# RUNTIME-ENV
# ------------------------------------------------------------------------------
FROM base AS runtime-env

ARG OS_VERSION_CODENAME
ARG POETRY_VERSION
ARG TASKFILE_VERSION

ENV PATH="/root/.local/bin:${PATH}"
ENV ANSIBLE_CONFIG=/usr/src/ansible.cfg

RUN echo 'export PATH="/root/.local/bin:$PATH"' >> /root/.bashrc
RUN echo 'export ANSIBLE_CONFIG=/usr/src/ansible.cfg' >> /root/.bashrc

# Docker repo
RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo "Types: deb\n\
URIs: https://download.docker.com/linux/debian\n\
Suites: $OS_VERSION_CODENAME\n\
Components: stable\n\
Signed-By: /etc/apt/keyrings/docker.asc" \
    > /etc/apt/sources.list.d/docker.sources

# Vagrant repo
RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg \
    && chmod a+r /etc/apt/keyrings/hashicorp-archive-keyring.gpg \
    && echo "Types: deb\n\
URIs: https://apt.releases.hashicorp.com\n\
Suites: $OS_VERSION_CODENAME\n\
Components: main\n\
Architectures: $(dpkg --print-architecture)\n\
Signed-By: /etc/apt/keyrings/hashicorp-archive-keyring.gpg" \
    > /etc/apt/sources.list.d/hashicorp.sources

# Install packages
RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        bridge-utils \
        dnsmasq-base \
        docker-ce-cli \
        ebtables \
        libguestfs-tools \
        libosinfo-bin \
        libvirt-clients \
        libvirt-daemon \
        libvirt-daemon-system \
        libvirt-dev \
        libxml2-dev \
        libxslt-dev \
        nfs-common \
        nfs-kernel-server \
        pipx \
        python3-apt \
        qemu-kvm \
        qemu-system \
        ruby-dev \
        ruby-fog-libvirt \
        ruby-libvirt \
        vagrant \
        virt-manager \
        virtinst \
        zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && find /var/log -type f -exec truncate -s 0 {} \;

# Vagrant configuration
RUN vagrant plugin install vagrant-libvirt

# Libvirt configuration
RUN sed -i '/unix_sock_group/c\unix_sock_group = "libvirt"' /etc/libvirt/libvirtd.conf

# Install Poetry
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install "poetry==$POETRY_VERSION"

# Install Taskfile
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- \
  -b /usr/local/bin -d v$TASKFILE_VERSION

# ------------------------------------------------------------------------------
# PROJECT-ENV
# ------------------------------------------------------------------------------
FROM runtime-env AS project-env

WORKDIR /usr/src

# Install dependencies
RUN --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=poetry.lock,target=poetry.lock \
    poetry install \
        --no-root \
        --no-interaction \
        --no-directory

# Install ansible-galaxy collections
RUN --mount=type=bind,source=requirements.yml,target=requirements.yml \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=poetry.lock,target=poetry.lock \
    poetry run \
    ansible-galaxy collection install -r requirements.yml

# ------------------------------------------------------------------------------
# RUNTIME
# ------------------------------------------------------------------------------
FROM project-env AS runtime

# Autologin service
COPY ./scripts/autologin.conf /etc/systemd/system/console-getty.service.d/
RUN chmod 0644 /etc/systemd/system/console-getty.service.d/autologin.conf

# Entrypoint
COPY ./scripts/docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/sbin/init"]
