galaxy_info:
  role_name: mise
  author: sjlex
  description: An Ansible role to configure mise.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - trixie
      - bookworm

  galaxy_tags:
    - mise

dependencies: []

collections:
  - sjlex.collection
