---
prerun: false

dependency:
  name: galaxy
  options:
    role-file: requirements.dev.yml
    requirements-file: requirements.dev.yml

driver:
  name: docker

platforms:
  # Debian 13 - Trixie
  - name: playbook-main_debian13_${MOLECULE_INSTANCE_ID}
    image: "python:3.13.12-trixie"
    pre_build_image: true

  # Debian 12 - Bookworm
  - name: playbook-main_debian12_${MOLECULE_INSTANCE_ID}
    image: "python:3.13.12-bookworm"
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

verifier:
  name: testinfra
