# Status bar
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-position top
set -g status-left-length 0
set -g status-right-length 0

set -g status-style 'fg=#959595,none'

set -g status-left "#[fg=#828282,bg=#000000] #S "
set -g status-right "#[fg=#050505,bg=#94C9FF]#{?client_prefix, P ,}#[fg=#828282,bg=#050505]#{?#{s/\\*//:window_flags},#{#[fg=#050505,bg=#C1FF94] #{s/\\*//:window_flags} #[fg=#828282,bg=#050505]},}#[fg=#828282,bg=#000000] %a %d-%m-%Y %I:%M %p "

# Messages
set -g message-style "fg=#E3E3E3,bg=#050505"

# Format window names
setw -g window-status-separator ""
setw -g window-status-format "#[fg=#828282,bg=#000000] #W "
setw -g window-status-current-format "#[fg=#c4c4c4,bg=#252525] #W "

# Panes
set -g pane-border-style "fg=#121212"
set -g pane-active-border-style "fg=#121212"

# Copy mode (fix for 3.6)
# set -g copy-mode-position-format "#[align=right][#{scroll_position}/#{history_size}]#{?search_timed_out, (timed out),#{?search_count, (#{search_count}#{?search_count_partial,+,} results),}}"
