---
prerun: false

dependency:
  name: galaxy
  options:
    role-file: requirements.dev.yml
    requirements-file: requirements.dev.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  # Debian 13 - Trixie
  - name: playbook-main-debian13-${MOLECULE_INSTANCE_ID}
    box: "debian/trixie64"
    pre_build_image: true
    cpu: 2
    memory: 1024

  # Debian 12 - Bookworm
  - name: playbook-main-debian12-${MOLECULE_INSTANCE_ID}
    box: "debian/bookworm64"
    pre_build_image: true
    cpu: 2
    memory: 1024

provisioner:
  name: ansible
  env:
    VAGRANT_DEFAULT_PROVIDER: libvirt
    ANSIBLE_ROLES_PATH: "../../roles"

verifier:
  name: testinfra
