---
- name: Manage Docker contexts
  when: docker_context | default([]) | length > 0
  block:
    - name: "Check if docker context exists for current user"
      ansible.builtin.command: docker context inspect "{{ item.name }}"
      loop: "{{ docker_context }}"
      register: _docker_context_check_user
      changed_when: false
      failed_when: false

    - name: "Create docker context for current user"
      ansible.builtin.command: docker context create --docker "host={{ item.item.endpoint }}" "{{ item.item.name }}"
      loop: "{{ _docker_context_check_user.results | default([]) }}"
      when:
        - _docker_context_check_user.skipped is not defined or not _docker_context_check_user.skipped
        - item.rc != 0

    - name: "Check if docker context exists for root"
      ansible.builtin.command: docker context inspect "{{ item.name }}"
      loop: "{{ docker_context }}"
      become: true
      become_user: root
      register: docker_context_check_root
      changed_when: false
      failed_when: false

    - name: "Create docker context for root"
      ansible.builtin.command: docker context create --docker "host={{ item.item.endpoint }}" "{{ item.item.name }}"
      loop: "{{ docker_context_check_root.results | default([]) }}"
      become: true
      become_user: root
      when:
        - docker_context_check_root.skipped is not defined or not docker_context_check_root.skipped
        - item.rc != 0

- name: Set default Docker context
  when: docker_context_default | default('') | length > 0
  block:
    - name: "Get current docker context for current user"
      ansible.builtin.command: docker context show
      register: _docker_context_current_user
      changed_when: false
      failed_when: false

    - name: "Set default docker context for current user"
      ansible.builtin.command: docker context use "{{ docker_context_default }}"
      when:
        - _docker_context_current_user.skipped is not defined or not _docker_context_current_user.skipped
        - _docker_context_current_user.stdout | default('') != docker_context_default

    - name: "Get current docker context for root"
      ansible.builtin.command: docker context show
      become: true
      become_user: root
      register: _docker_context_current_root
      changed_when: false
      failed_when: false

    - name: "Set default docker context for root"
      ansible.builtin.command: docker context use "{{ docker_context_default }}"
      become: true
      become_user: root
      when:
        - _docker_context_current_root.skipped is not defined or not _docker_context_current_root.skipped
        - _docker_context_current_root.stdout | default('') != docker_context_default
