---
- name: "Get __htop_installed_version"
  block:
    - name: "Check if htop is installed"
      ansible.builtin.command: "dpkg-query -W -f='${Version}' {{ __htop_package_name }}"
      register: __htop_dpkg_check
      failed_when: false
      changed_when: false

    - name: "Set htop version fact"
      ansible.builtin.set_fact:
        __htop_installed_version: "{{ __htop_dpkg_check.stdout if __htop_dpkg_check.rc == 0 else '' }}"

- name: "Copy htoprc (htop 3.2.*)"
  ansible.builtin.copy:
    src: 3.2/htoprc
    dest: '{{ ansible_facts["env"]["HOME"] }}/.config/htop/'
    mode: "0644"
  when: __htop_installed_version.startswith("3.2")

- name: "Copy htoprc (htop 3.4.*)"
  ansible.builtin.copy:
    src: 3.4.1/htoprc
    dest: '{{ ansible_facts["env"]["HOME"] }}/.config/htop/'
    mode: "0644"
  when: __htop_installed_version.startswith("3.4")
